version: '3'
services:
  webserver:
    image: library/nginx:1.19-alpine
    volumes:
      - ./config/nginx/dev:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - reactServer
  npm:
    image: library/node:14.10-alpine
    volumes:
      - ./:/site
    working_dir: /site
    entrypoint: npm
  reactServer:
    image: library/node:14.10-alpine
    container_name: react_server
    volumes:
      - ./:/site
    working_dir: /site
    tty: true
    entrypoint: npm
    command: start
